# Linkers for non-native Linux targets are routed through small wrapper scripts
# so native builds on Linux use the system linker while macOS keeps using the
# cross toolchains.
[target.aarch64-unknown-linux-gnu]
linker = "scripts/linkers/aarch64-unknown-linux-gnu.sh"

[target.x86_64-unknown-linux-gnu]
linker = "scripts/linkers/x86_64-unknown-linux-gnu.sh"

[target.x86_64-pc-windows-gnullvm]
linker = "x86_64-w64-mingw32-gcc"

# If you were targeting a 32-bit Pi, you would add this section:
# [target.armv7-unknown-linux-gnueabihf]
# linker = "arm-linux-gnueabihf-gcc"
